services:
  nginx:
    container_name: laravel11x_nginx
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./www/public
        target: /var/www/public
    depends_on:
      - php
    environment:
      TZ: Asia/Tokyo

  php:
    container_name: laravel11x_php
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
    volumes:
      - type: bind
        source: ./www
        target: /var/www
    healthcheck:
      test: ['CMD', 'docker-healthcheck']
      interval: 30s
      timeout: 3s
      retries: 3

  database:
    container_name: laravel11x_pgsql
    build:
      context: ./
      dockerfile: docker/database/Dockerfile
    volumes:
      - pgsql_data:/var/lib/postgresql/data:rw
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel_user
      POSTGRES_PASSWORD: secret
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
    command: >
      -c log_destination=stderr
      -c log_statement=all 
      -c log_connections=on 
      -c log_disconnections=on
      -c logging_collector=on
      -c log_line_prefix='[%t]%u %d %p[%l]'
      -c log_min_duration_statement=3000
    logging:
      options:
        max-size: "10k"
        max-file: "5"

  tbls:
    container_name: laravel11x_dbdoc
    image: k1low/tbls:latest
    volumes:
      - ./docs/schema:/schema
    command: doc postgres://laravel_user:secret@mokkedano_pgsql:5432/laravel?sslmode=disable ./schema --force
    profiles:
      - dbdoc

volumes:
  pgsql_data:
    driver: local
